### ISSUE TITLE
As a SKC member, I want to have API which is updating the articles on the main page

### ISSUE THREAD

**Issue by TophatPigeonno** [SKC-Team11/SKCrime#1]

**Comment by AlexGit123** [comment]
Acceptance Criteria
GIVEN: As an SKC member I want to see recent articles fetched from the DB 
WHEN: A new article is uploaded the API is updated and pushed to the DB
THEN: The article should appear on the main page

WHEN: An article is uploaded the API does not push to the DB 
THEN: A new article would not appear on the main page
