### ISSUE TITLE
As a user, I want to be able to use the search engine, so I can find the information that I am looking for

### ISSUE THREAD

**Issue by TophatPigeonno** [SKC-Team11/SKCrime#2]

**Comment by AlexGit123** [comment]
**Acceptance Criteria:**
GIVEN: As a user, I want to be able to use the search engine so I can find the information I am looking for 
WHEN: I go to the application and use the search bar
THEN: it should show me the information that I searched for

WHEN: I go to the application and use the search bar but it doesn't exist
THEN: A message should pop up saying that there is no available information/no articles
