### ISSUE TITLE
As a user, I want the map to be more fluent by having boundaries for the map edges so that it is more visually appealing

### ISSUE THREAD

**Issue by TophatPigeonno** [SKC-Team11/SKCrime#5]

**Comment by BogomilDochev** [comment]
WHEN: User is on the map and there are clear boundaries for the map edges
THEN: User can easily understand which country is clicked by him/her

WHEN: User is on the map and there are not clear boundaries for the map edges
THEN: User would be confused about the country that is clicked by him/her which
